/**
 * Slack Integration
 *
 * Posts account digests and alerts to Slack channels.
 * Also reads channel history for context.
 *
 * Required env vars:
 *   SLACK_BOT_TOKEN   - Bot User OAuth Token (xoxb-...)
 *
 * Required bot scopes:
 *   channels:read, channels:history, chat:write, chat:write.public
 *
 * Setup: https://api.slack.com/apps → Create New App → Bot Token Scopes
 */

import { WebClient } from '@slack/web-api';

const slack = new WebClient(process.env.SLACK_BOT_TOKEN || '');

/**
 * Find a channel by name (e.g., "acc-datadog").
 * Returns channel ID or null.
 */
export async function findChannel(channelName: string): Promise<string | null> {
  try {
    // Remove # prefix if present
    const name = channelName.replace(/^#/, '');

    let cursor: string | undefined;
    do {
      const result = await slack.conversations.list({
        types: 'public_channel,private_channel',
        limit: 200,
        cursor,
      });

      const match = result.channels?.find((c) => c.name === name);
      if (match?.id) return match.id;

      cursor = result.response_metadata?.next_cursor;
    } while (cursor);

    return null;
  } catch (err) {
    console.error(`Failed to find channel ${channelName}:`, err);
    return null;
  }
}

/**
 * Create a channel if it doesn't exist. Returns channel ID.
 */
export async function ensureChannel(channelName: string): Promise<string | null> {
  const name = channelName.replace(/^#/, '');

  // Check if it already exists
  const existing = await findChannel(name);
  if (existing) return existing;

  try {
    const result = await slack.conversations.create({ name });
    return result.channel?.id || null;
  } catch (err: unknown) {
    // Channel might already exist (race condition) — try finding it again
    if (err && typeof err === 'object' && 'data' in err) {
      const slackErr = err as { data?: { error?: string } };
      if (slackErr.data?.error === 'name_taken') {
        return findChannel(name);
      }
    }
    console.error(`Failed to create channel ${name}:`, err);
    return null;
  }
}

/**
 * Read recent messages from a channel for context.
 */
export async function getChannelHistory(
  channelId: string,
  limit: number = 50
): Promise<{ author: string; text: string; ts: string }[]> {
  try {
    const result = await slack.conversations.history({
      channel: channelId,
      limit,
    });

    return (result.messages || []).map((msg) => ({
      author: msg.user || msg.bot_id || 'unknown',
      text: msg.text || '',
      ts: msg.ts || '',
    }));
  } catch (err) {
    console.error(`Failed to read channel history:`, err);
    return [];
  }
}

interface DigestSection {
  title: string;
  emoji: string;
  content: string;
}

/**
 * Post an account digest to a Slack channel.
 * Uses Block Kit for rich formatting.
 */
export async function postAccountDigest(
  channelId: string,
  accountName: string,
  sections: DigestSection[],
): Promise<boolean> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const blocks: any[] = [
      // Header
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `📊 Account Digest — ${accountName}`,
        },
      },
      { type: 'divider' },
    ];

    // Add each section
    for (const section of sections) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `${section.emoji} *${section.title}*\n${section.content}`,
        },
      });
    }

    // Footer
    blocks.push(
      { type: 'divider' },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `🤖 Generated by Pulse · Sources: Grafana, Gong, Pylon, Product Data · ${new Date().toLocaleString()}`,
          },
        ],
      },
    );

    await slack.chat.postMessage({
      channel: channelId,
      text: `📊 Account Digest — ${accountName}`, // Fallback for notifications
      blocks,
      unfurl_links: false,
    });

    return true;
  } catch (err) {
    console.error(`Failed to post digest to channel:`, err);
    return false;
  }
}

/**
 * Post a risk alert to a channel.
 */
export async function postRiskAlert(
  channelId: string,
  accountName: string,
  riskScore: number,
  signals: string[],
): Promise<boolean> {
  try {
    const emoji = riskScore >= 60 ? '🔴' : riskScore >= 30 ? '🟡' : '🔵';

    await slack.chat.postMessage({
      channel: channelId,
      text: `${emoji} Risk Alert — ${accountName} (Score: ${riskScore}%)`,
      blocks: [
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `${emoji} *Risk Alert — ${accountName}*\nRisk score: *${riskScore}%*`,
          },
        },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: signals.map((s) => `• ${s}`).join('\n'),
          },
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `🤖 Pulse Risk Radar · ${new Date().toLocaleString()}`,
            },
          ],
        },
      ],
      unfurl_links: false,
    });

    return true;
  } catch (err) {
    console.error(`Failed to post risk alert:`, err);
    return false;
  }
}

/**
 * Post a pre-call brief to a channel.
 */
export async function postPreCallBrief(
  channelId: string,
  accountName: string,
  meetingTitle: string,
  brief: string,
): Promise<boolean> {
  try {
    await slack.chat.postMessage({
      channel: channelId,
      text: `📋 Pre-Call Brief — ${accountName}: ${meetingTitle}`,
      blocks: [
        {
          type: 'header',
          text: {
            type: 'plain_text',
            text: `📋 Pre-Call Brief — ${meetingTitle}`,
          },
        },
        {
          type: 'section',
          text: { type: 'mrkdwn', text: brief },
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `🤖 Pulse · Meeting starts in 30 min · ${new Date().toLocaleString()}`,
            },
          ],
        },
      ],
      unfurl_links: false,
    });

    return true;
  } catch (err) {
    console.error(`Failed to post pre-call brief:`, err);
    return false;
  }
}
